### ISSUE TITLE
Using "appendices" wrapper causes PDF2 failure or error

### ISSUE THREAD

**Issue by robander** [dita-ot/dita-ot#2092]
Using the latest development code, I am trying to reuse a set of appendices from one bookmap inside of another, so I wrapped them in the `<appendices>` element:

``` xml
<appendices id="app">
<appendix href="bookapp1.dita"/>
<appendix href="bookapp2.dita"/>
</appendices>
```

When `@href` is specified on the `<appendices>` element, the PDF looks fine. When there is no `@href` as in the sample above, output is broken. AH returns a PDF without the two topics (though the titles appear in the contents / bookmarks). It also generates the following errors:

```
      [ahf] Error Code  : 10769 (2A11)
      [ahf] Unresolved id value: "_OPENTOPIC_TOC_PROCESSING_d68e2780".
      [ahf] Line 1, Col 20232, file:///C:/Users/IBM_AD~1/AppData/Local/Temp/temp20151008163148010/topic.fo
      [ahf] Error Level : 2
      [ahf] Error Code  : 10769 (2A11)
      [ahf] Unresolved id value: "_OPENTOPIC_TOC_PROCESSING_d68e2867".
      [ahf] Line 1, Col 20849, file:///C:/Users/IBM_AD~1/AppData/Local/Temp/temp20151008163148010/topic.fo
```

When I try with FOP, I get Java errors and no PDF.

**Comment by robander** [comment]
Looks like #1428 from a few years back added some level of support for `<appendices>` that did not reference a topic, but that's missing now.

**Comment by eerohele** [comment]
:+1: encountered this in a customer case.

**Comment by adambhere** [comment]
Tried with Apache FOP and no attributes on the element. Got no errors, but the PDF output does not include the individual appendices (appendix elements and their content). In DITA OT 1.8.5, it was possible to wrap any number of <appendix> elements in <appendices>, with appendices including neither @navtitle nor @href, and the individual <appendix> elements were rendered in PDF. 

A work-around seems to be to add @navtitle or @href to the <appendices> element. This causes the nested <appendix> elements to be rendered, but results in an unwanted "Appendix" page, similar to a part front page. 

The ideal solution would be to render <appendices> only if a @navtitle or @href is provided, otherwise, render only the nested <appendix> elements. In other words the following:

<appendix href="appendix_topic1.dita" />
<appendix href="appendix_topic2.dita" />

... and this:
<appendices>
  <appendix href="appedix_topic1.dita" />
  <appendix href="appendix_topic2.dita" />
</appendices>

 ... should both result in  only appendix_topic{x}.dita being rendered.

I'd be happy to override the existing behaviour in our PDF plug-in, but have not yet identified the code area to modify: any tips would be appreciated.

**Comment by infotexture** [comment]
@adambhere Looks like the XML portions of your comment were lost.

You should be able to edit your previous comment and wrap inline XML code wrap with backtick quotes (\`) like this: `` `<xml>` ``

or use a [fenced code block](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) for syntax highlighting.

**Comment by eerohele** [comment]
This issue also occurs with `<chapter>` elements that have no navtitle or `@href`. Presumably with other similar bookmap elements, too.

**Comment by drmacro** [comment]
A chapter topicref with no navtitle or referenced resource is not a meaningful use of chapter in the context of a bookmap--chapters are intended to be titled things. This is, I realize, orthogonal to the apparent failure to account for topicgroup elements but nevertheless a chapter with no reference or title is not a valid use case.

**Comment by eerohele** [comment]
I guess one potential fix would be something along the lines of (untested):

```xslt

  <xsl:function name="dita-ot:get-navtitle" as="node()?">
    <xsl:param name="el" as="element()"/>

    <xsl:sequence select="
      ($el/*[contains(@class, ' map/topicmeta ')]
          /*[contains(@class, ' topic/navtitle ')],
       $el/@navtitle)[1]
    "/>
  </xsl:function>

  ....

  <xsl:template mode="generatePageSequences" priority="1"
    match="
      *[contains(@class, ' map/topicref ')]
       [empty(dita-ot:get-navtitle(.))]
       [not(normalize-space(@href))]
       [exists(*)]
    ">
    <xsl:apply-templates mode="#current"/>
  </xsl:template>
```

Although it would probably be better to explicitly specify the `@class` values rather than use `map/topicref`.

**Comment by infotexture** [comment]
Revisiting this with latest code from `develop`, wrapping existing `<appendix>` elements in `<appendices>` no longer throws errors or prevents appendix topics from being rendered to output, but the page numbers in the corresponding ToC entries are missing.

Adding a `@navtitle` per [Adam's comment](https://github.com/dita-ot/dita-ot/issues/2092#issuecomment-212410619) above restores the ToC page numbers, but still generates the extra "Appendix" page and prefixes the navtitle with **Chapter :** 

<img width="428" alt="appendices-toc-errors-issue-2092" src="https://cloud.githubusercontent.com/assets/129995/22088145/460df05e-dde2-11e6-86e2-98e189b10a1f.png">

**Comment by robander** [comment]
Testing with latest `develop`, using FOP, I'm still getting bad output - missing content and broken links in the TOC / bookmarks.

I put together a fix for #2468 and was about to submit a pull request when I realized it probably had something in common with this one - I think something similar to @eerohele 's page sequence fix will work. That said, the same issue shows up with other elements (`chapter` with no title/href but with subtopics, `part` with the same, etc), and it's complicated by the fact that all of these currently match based on `@class` and then call a different named template.

**Comment by robander** [comment]
I think it's reasonable for an author to use `<appendices>` to group a bunch of `<appendix>` elements (I've run into that and so have others).

At the same time I agree with what @drmacro said above about the validity of this source markup when it comes to `<chapter>`:
> A chapter topicref with no navtitle or referenced resource is not a meaningful use of chapter in the context of a bookmap--chapters are intended to be titled things. This is, I realize, orthogonal to the apparent failure to account for topicgroup elements but nevertheless a chapter with no reference or title is not a valid use case.

The same issue is at the root of all of these - the code assumes that you won't use grouping elements in the top level of any map. Regardless of whether this is meaningful, the current output is broken - anything inside the empty `<chapter>` is there in the TOC / bookmarks but the actual content is missing. So I think the question is whether they should effectively bump up into chapters, or if we should try to treat them as something else -- what's the graceful fallback?

The fix I'm working on now will bump them up to create chapter processing. They don't become part of the chapter numbering sequence, because numbering also assumes the chapter itself provides a title or `@href`. For now I think that's fine as a fallback - you get the content, and if your formatting is a bit off, that's sort of what you're asking for with the odd markup. Same goes for `part`, `appendix`, etc.

**Comment by robander** [comment]
On second thought ... turning the graceful fallback into "just treat this as a non-bookmap top-level branch" looks like it is simpler to code + gives results that are just as good for this edge case, so leaning that way.

**Comment by jelovirt** [comment]
Fixed by #2683

**Comment by infotexture** [comment]
Testing this with latest code from `develop` after fixes from #2683, and the following markup

```xml
  <appendices navtitle="Appendices">
```

I still see the issues described in my [comment](https://github.com/dita-ot/dita-ot/issues/2092#issuecomment-273640632) above:

> still generates the extra "Appendix" page and prefixes the navtitle with **Chapter :**

_Without_ the navtitle, it now works as if there were no `<appendices>` wrapper as Adam [suggested](https://github.com/dita-ot/dita-ot/issues/2092#issuecomment-212410619), but if someone _does_ define a navtitle with the intention of creating a visible grouping in the output, they certainly wouldn't expect this text to be prefixed with **“Chapter :”** in the ToC, since appendixes are _not_ chapters. 

I see the logic in preserving an authored navtitle and placing it on the Appendix cover page like for Parts, but it seems we should at least drop the prefix from the ToC to show only the navtitle (as in the PDF bookmarks).

**Comment by robander** [comment]
@infotexture yes - that is correct. That's ... not really the same as the original issue, which was that if I have plain `<appendices>` with no title or `@href` I previously got errors + every actually appendix topic was missing.

It's probably worth having another issue for this (I'd like to be able to fix it too but don't have a pull request in the queue for it, so an issue will keep it from getting lost).
