### ISSUE TITLE
XHTML transtype problem (and solution): Content from RTL tables is aligned to the left 

### ISSUE THREAD

**Issue by dan-caprioara** [dita-ot/dita-ot#2302]
This is caused by DITA-OT 2.x generating a style attribute with "text-align:left" on all the table cells, no matter if they have or not the the align attribute set into the source,

**How to reproduce:**

Insert a table with arabic content into a topic. Put xml:lang="ar" and dir="rtl" on the root of the topic, then transform it to XHTML. You can use this fragment below, but the problem can be seen on english content in a RTL table also.
```

    <table id="table_chp_lxj_hl" rowsep="1" colsep="1" dir="rtl">
      <tgroup cols="2">
        <colspec colnum="1" colname="col1"/>
        <colspec colnum="2" colname="col2"/>
        <tbody>
          <row>
            <entry namest="col1" nameend="col2">النبات الحبي</entry>
          </row>
          <row>
            <entry namest="col1" nameend="col2"> النباتات الحبية
              المختلفة و منتجاتها</entry>
          </row>
        </tbody>
      </tgroup>
    </table>

```

The text from table cells are aligned to the left inside each of the cells.
This is wrong, it should be aligned to the right. For LTR tables it should be to the left.

The problem is in the file:

`DITA-OT2.x/plugins/org.dita.xhtml/xsl/xslhtml/dita2htmlImpl.xsl`

in template:

`<xsl:template name="doentry">`

Here is computed the style attribute for each of the table entries. There are some default values for text-align and vertical-align set to "left" and "top". The default values should not be specified, so the browser can infer them from the parent elements/styles.

**The solution is:**
Remove the xsl:otherwise blocks.
```

 <xsl:variable name="align" as="xs:string?">
        <xsl:choose>
         <xsl:when test="@align">
           <xsl:value-of select="@align"/>
         </xsl:when>
          <xsl:when test="$group/@align">
            <xsl:value-of select="$group/@align"/>
          </xsl:when>
          <xsl:when test="$colspec/@align">
            <xsl:value-of select="$colspec/@align"/>
          </xsl:when>
          <!-- PATCH START   -->          
          <!--
          <xsl:otherwise>
            <xsl:value-of select="$table.align-default"/>
          </xsl:otherwise>
          -->
        </xsl:choose>
      </xsl:variable>
      <xsl:if test="exists($align)">
        <xsl:text>text-align:</xsl:text>
        <xsl:value-of select="$align"/>
        <xsl:text>;</xsl:text>
      </xsl:if>
      <xsl:variable name="valign" as="xs:string?">
        <xsl:choose>
         <xsl:when test="@valign">
           <xsl:value-of select="@valign"/>
         </xsl:when>
         <xsl:when test="$row/@valign">
           <xsl:value-of select="$row/@valign"/>
         </xsl:when>
          <xsl:when test="$body/@valign">
            <xsl:value-of select="$body/@valign"/>
          </xsl:when>
          <!--  PATCH START   -->          
          <!--
          <xsl:otherwise>top</xsl:otherwise>
          -->
       </xsl:choose>

```

**Comment by jelovirt** [comment]
For reference [9901:1999 XML Exchange Table Model DTD](https://www.oasis-open.org/specs/tm9901.html).

**Comment by robander** [comment]
Looking at the referenced exchange model, I see this about the alignment value in an entry (section 3.7.3.7:
>     Default
>
>    IMPLIED (means use value from nearest applicable colspec of the nearest ancestral tgroup. If none, then “left”.)

Earlier in 3.2.3.3, description of alignment on tgroup:
>     Default
>
>    IMPLIED (means use value from stylesheet if any, else “left”.)

And finally at the start of the section, 3.1.1:
> **3.1.1. General**
>
> The table element markup identifies a table.
>
> Elements inside a table may at times inherit default values from the attributes on the containing table. Furthermore, a table element may have some stylesheet associated with it that may provide default values for some or all of its attributes.
> 
> If a table element has no explicit specification for an attribute but does have an associated style sheet that gives a specification for this attribute, then the stylesheet value shall be used as the value that is inherited from this element.

So, the `<tgroup>` definition says that a default alignment may be taken from a "stylesheet". Section 3.1.1 gives a general description of a stylesheet that may be used to set up defaults for attribute values. I read this to mean that it is legal, per the exchange model, for our stylesheet to set a default alignment of RTL for bi-di languages. [Also: I think that's just the right thing to do, regardless of what's in the exchange model DTD].

**Comment by raducoravu** [comment]
By "stylesheet" you mean CSS, right? So can we issue a pull request with the proposed changes?

**Comment by robander** [comment]
I don't think stylesheet (in that specification) is defined any more than what I quoted above. I read it to mean "anything that is used to style the document" - so it could just as easily be in the XSLT, setting a default of right (or leaving the default off for BiDi to let browsers handle it). My initial reaction would have been to update the XSLT to set alignment to right in any situation where the table itself is in an RTL context -- 1) closest `@dir` value is "rtl", or 2) no `@dir` specified and current language context would default to RTL.

**Comment by dan-caprioara** [comment]
In order to do the text alignment the browsers just need a correct RLT/LTR context (the dir attributes set on the ancestor HTML elements),so dealing with this from XSLT is redundant in my opinion.
Anyway, this is a a serious bug and no matter the solution, it needs to be fixed.

**Comment by robander** [comment]
I think my preference would be to just remove the default (rather than calculating the default and specifying alignment in every case. This would allow browsers to do the right thing based on already-specified alignment or stylesheets. @jelovirt not sure if you are still following this one or have any opinion.

**Comment by jelovirt** [comment]
I'm the one who implemented the strict CALS based processing. The problem with CALS (OASIS table exchange model) is that it's ethnocentric from US perspective and does not recognize existence of LTR languages. The best option would be to move from left/right value set to start/end and just ignore what CALS/OASIS says.

**Comment by robander** [comment]
I'll update this one to use a stylesheet default of no value, which in my reading is compatible with the OASIS exchange model, and (compatible or not) will restore the old processing of no-default.

**Comment by jelovirt** [comment]
Fixed in #2368

**Comment by raducoravu** [comment]
Great, thanks guys.

**Comment by dan-caprioara** [comment]
It is not solved for the _vertical_ alignment. The cells are still aligned to the top by default.
It should be:
```
<xsl:variable name="valign" as="xs:string?">
        <xsl:choose>
         <xsl:when test="@valign">
           <xsl:value-of select="@valign"/>
         </xsl:when>
         <xsl:when test="$row/@valign">
           <xsl:value-of select="$row/@valign"/>
         </xsl:when>
          <xsl:when test="$body/@valign">
            <xsl:value-of select="$body/@valign"/>
          </xsl:when>
          <!--  PATCH START   -->          
          <!--
          <xsl:otherwise>top</xsl:otherwise>
          -->
       </xsl:choose>
```
