### ISSUE TITLE
NullPointerException in AbstractReaderModule

### ISSUE THREAD

**Issue by raducoravu** [dita-ot/dita-ot#3007]
I'm attaching a sample DITA project, published to PDF using DITA OT 3.1 the following NullPointerException is reported:

```
D:\projects\oxygen-dita-ot-3.x\build.xml:45: The following error occurred while executing this line:
D:\projects\oxygen-dita-ot-3.x\plugins\org.dita.base\build_preprocess2.xml:175: java.lang.NullPointerException
	at org.dita.dost.module.reader.AbstractReaderModule.addToWaitList(AbstractReaderModule.java:535)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.dita.dost.module.reader.TopicReaderModule.readStartFile(TopicReaderModule.java:133)
	at org.dita.dost.module.reader.TopicReaderModule.execute(TopicReaderModule.java:70)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
```

[npe_pdf_reader_module.zip](https://github.com/dita-ot/dita-ot/files/2144456/npe_pdf_reader_module.zip)

From what I looked, probably just guarding the NPE should be fine. There is a key definition there with a copy-to and the key is later referenced with a related link from a topic. Just guarding the NPE and then publishing to PDF the related link to the key seems to work.

**Comment by raducoravu** [comment]
Problem was reported here:
https://groups.yahoo.com/neo/groups/dita-users/conversations/messages/43705

**Comment by infotexture** [comment]
Fixed for 3.1.1 w/ PR #3015.

**Comment by raducoravu** [comment]
Problem still occurs in DITA OT 3.2.1:

    BUILD FAILED
    D:\projects\eXml\frameworks\dita\DITA-OT3.x\build.xml:46: The following error occurred while     executing this line:
    D:\projects\eXml\frameworks\dita\DITA-OT3.x\plugins\org.dita.base\build_preprocess2.xml:176:     java.lang.NullPointerException
	at org.dita.dost.module.reader.AbstractReaderModule.addToWaitList(AbstractReaderModule.java:545)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.dita.dost.module.reader.TopicReaderModule.readStartFile(TopicReaderModule.java:133)
	at org.dita.dost.module.reader.TopicReaderModule.execute(TopicReaderModule.java:70)
	at org.dita.dost.ant.ExtensibleAntInvoker.execute(ExtensibleAntInvoker.java:169)

**Comment by raducoravu** [comment]
NPE still exists in DITA OT 3.5.4

**Comment by raducoravu** [comment]
Thanks @jelovirt for investing time in the preprocess2 bugs, it will be interesting when the preprocess2 fixes make it in an official release to switch our WebHelp and PDF-CSS based plugins to it and see what other our automatic tests find.
